global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'rest-http'
    metrics_path: '/metrics'
    static_configs:
    - targets: ['rest-http.app.svc.cluster.local:8080']
